server:
  port: 8080

spring:
  application:
    name: activemq-demo
  activemq:
    # MQ所在的服务器的地址
    broker-url: tcp://192.168.154.129:61616
    # 是否使用内置的MQ， true  使用； fale  不使用
    in-memory: false
    # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    non-blocking-redelivery: false
    user: admin
    password: admin
#  jms:
#    # 消息类型 默认值为false，  false：queue true：topic
#    pub-sub-domain: true
